### PR TITLE
Fix for issue #919

### LINKED ISSUE #919: Pick&place and image marker augmentations missing
The pick and place and the image marker augmentations are missing in the list - although they are listed in the BrandConfiguration.cs under spareListOfAugmentations, which should be responsible for activating the available augmentations based on the platform. Possibly this is because 'pick&place' is used and not 'pickandplace' (the part of the variable name and content type in ContentType.cs)? Similar with 'image marker' which might have to be 'imagemarker' to work?

RC 1.9, 27.5.2022, iPad

### PR DESCRIPTION
**Pull request by jafarigit**
This will brings back the missing augmentation (image marker and pick and place) to the mobile version
Closes #919

### CODE REVIEW

**Review by fwild — CHANGES_REQUESTED** [review]
Can you please also fix the line 40 for hololens?

**Comment by fwild** [comment]
Or was the hololens not affected?

**Review by fwild — APPROVED** [review]

File: Assets/MirageXR/Player/Scripts/Managers/BrandManager.cs [hunk 1]
```diff
@@ -35,7 +35,7 @@ public class BrandManager : MonoBehaviour
 
 #if UNITY_ANDROID || UNITY_IOS
 
-    private readonly string[] spareListOfAugmentations = { "image", "video", "audio", "ghost", "label", "act", "vfx",  "model", "character", "pick&place", "image marker", "plugin" };
+    private readonly string[] spareListOfAugmentations = { "image", "video", "audio", "ghost", "label", "act", "vfx",  "model", "character", "pickandplace", "imagemarker", "plugin" };
```
Comment (cawke) [inline Assets/MirageXR/Player/Scripts/Managers/BrandManager.cs:38]: is there any reason to keep two identical lists or can we keep just one? 
```
BrandManager.spareListOfAugmentations
BrandConfiguration.spareListOfAugmentations
```
