### PR TITLE
Hot fix pick and place

### LINKED ISSUE #1260: Pick&place errors from demo
The placement of the arrow was forgotten and it was not possible to minimize the menu and press next to get to the step with Pick&place.

### PR DESCRIPTION
**Pull request by robhillman97**
Fix for pick and place NRE

closes #1260

### CODE REVIEW

File: Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs [hunk 1]
```diff
@@ -134,39 +134,45 @@ private void LoadPickAndPlacePositions()
...
             }
-
-            string jsonPath = Path.Combine(_activityManager.ActivityPath, $"pickandplaceinfo/{_myObj.poi}.json");
-
-            // delete the exsiting file first
-            if (File.Exists(jsonPath))
+            catch (Exception e) 
             {
-                File.Delete(jsonPath);
+                Debug.Log("Pick and Place Exception " + e);
```
Comment (cawke) [inline Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs]:
```suggestion
                Debug.LogError("Pick and Place Exception " + e); 
```

File: Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs [hunk 2]
```diff
@@ -134,39 +134,45 @@ private void LoadPickAndPlacePositions()
...
+                    modelID = _pickComponent.MyModelID,
+                    targetObjectPosition = _targetObject.localPosition,
+                    targetObjectScale = _targetObject.localScale,
+                    resetPosition = _pickComponent.ResetPosition,
+                    resetRotation = _pickComponent.ResetRotation,
+                    moveMode = _pickComponent.MoveMode,
+                };
+
+                string pickAndPlaceData = JsonUtility.ToJson(positions);
+                if (!Directory.Exists($"{_activityManager.ActivityPath}/pickandplaceinfo "))
```
Comment (cawke) [inline Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs]:
```suggestion
                if (!Directory.Exists($"{_activityManager.ActivityPath}/pickandplaceinfo"))
```

File: Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs [hunk 3]
```diff
@@ -198,7 +204,7 @@ private void DeletePickAndPlaceData(ToggleObject toggleObject)
 
         private void OnDestroy()
         {
-            SavePositions();
+           SavePositions();
         }
```
Comment (cawke) [inline Assets/MirageXR/Common/Scripts/CombinedEditor/ActionDetailView/Annotation Editors/PickAndPlace/PickAndPlaceController.cs]: revert

File: Assets/MirageXR/Player/Scripts/Managers/Activity/ActivityManager.cs [hunk 4]
```diff
@@ -359,6 +359,9 @@ public async Task DeactivateAction(string id, bool doNotActivateNextStep = false
         {
             if (!_isSwitching)
             {
+                await Task.Yield();
```
Comment (cawke) [inline Assets/MirageXR/Player/Scripts/Managers/Activity/ActivityManager.cs]: I'm not sure that `Yield` is needed here.

**Review by cawke — CHANGES_REQUESTED** [review]

**Review by cawke — APPROVED** [review]
