### PR TITLE
fixed model animations

### LINKED ISSUE #1928: play model animation
Play embedded animation for sketchfab imports

### PR DESCRIPTION
**Pull request by fwild**
resolves #1928 

To test: 
* search for faw56 and import the readplayer me avatar (= export from mixamo, with an animation attached).
* search for "animation" and pick anything, e.g. dragon

### CODE REVIEW

**Comment by fwild** [comment]
@cawke please check whether lines 167-181 are really not needed - they are the culprit that caused the animations not to play (possibly amongst other things: animations were attached to a parent-parent object of where the gltfast importer attaches them already; possibly the import settings needed animation import to be set to legacy; possibly some of the other animation flags were not explicitly set and needed).

File: Assets/MirageXR/ContentTypes/3DModel/Model.cs [hunk 1]
```diff
@@ -126,65 +133,92 @@ private async Task<bool> LoadGltf(ToggleObject content)
...
             var modelTransform = transform;
             var startPos = modelTransform.position + modelTransform.forward * -0.5f + modelTransform.up * -0.1f;
-
+            
             model.transform.SetParent(modelTransform);
 
+            /*
+             * ALEX: please check this - I don't think it is needed and it prevented the animation 
+             * from being played
+             *
```
Comment (cawke) [inline Assets/MirageXR/ContentTypes/3DModel/Model.cs]: Yes, I don't think it's necessary. but we need to understand that models can have different sizes and it would be nice to have a tool that will fit the loaded model into an adequate size (also so that we can specify the original size of the model)

File: Assets/MirageXR/ContentTypes/3DModel/Model.cs [hunk 2]
```diff
@@ -126,65 +133,92 @@ private async Task<bool> LoadGltf(ToggleObject content)
...
+            if (legacyAnimation != null)
+            {
+                Debug.Log("playing animation (with data from gltfast scene instantiator).");
+
+                legacyAnimation.clip = _gltf.GetAnimationClips()[0];
+                legacyAnimation.clip.wrapMode = UnityEngine.WrapMode.Loop;
+                legacyAnimation.clip.legacy = true;
+                legacyAnimation.clip.EnsureQuaternionContinuity();
+                legacyAnimation.playAutomatically = true;
+                legacyAnimation.Play(_gltf.GetAnimationClips()[0].name);
```
Comment (cawke) [inline Assets/MirageXR/ContentTypes/3DModel/Model.cs]: add a null check

**Review by cawke — CHANGES_REQUESTED** [review]

File: Assets/MirageXR/ContentTypes/3DModel/Model.cs (hunk 1 above)
Comment (fwild) [reply Assets/MirageXR/ContentTypes/3DModel/Model.cs]: I am not quite sure what broke it - there was a warning floating by that said something about "size set to infinite" or some such, so I guess it was simply too small for the animation component to accept.

File: Assets/MirageXR/ContentTypes/3DModel/Model.cs (hunk 2 above)
Comment (fwild) [reply Assets/MirageXR/ContentTypes/3DModel/Model.cs]: added.

File: Assets/MirageXR/ContentTypes/3DModel/Model.cs (hunk 1 above)
Comment (fwild) [reply Assets/MirageXR/ContentTypes/3DModel/Model.cs]: I checked again, and it turns out the mode renaming was the real culprit, so I restored all the resize functions and only commented this out:
```
// model.name = _obj.option;
```
Is this model.name relevant anywhere? I think not, right?

Comment (cawke) [reply Assets/MirageXR/ContentTypes/3DModel/Model.cs]: I guess.

File: Assets/MirageXR/ContentTypes/3DModel/Model.cs [hunk 3]
```diff
@@ -126,22 +133,40 @@ private async Task<bool> LoadGltf(ToggleObject content)
...
+                if (clips.Length > 0)
+                {
+                    legacyAnimation.clip = clips[0];
+                    legacyAnimation.clip.wrapMode = UnityEngine.WrapMode.Loop;
+                    legacyAnimation.clip.legacy = true;
+                    legacyAnimation.clip.EnsureQuaternionContinuity();
+                    legacyAnimation.playAutomatically = true;
+                    legacyAnimation.Play(clips[0].name);
+                }
+            }
```
Comment (cawke) [inline Assets/MirageXR/ContentTypes/3DModel/Model.cs]:
```suggestion
                var clips = _gltf.GetAnimationClips();
                if (clips != null && clips.Length > 0 && clips[0] != null)
                {
                    legacyAnimation.clip = clips[0];
                    legacyAnimation.clip.wrapMode = UnityEngine.WrapMode.Loop;
                    legacyAnimation.clip.legacy = true;
                    legacyAnimation.clip.EnsureQuaternionContinuity();
                    legacyAnimation.playAutomatically = true;
                    legacyAnimation.Play(clips[0].name);
                }
            }
```

**Review by cawke — CHANGES_REQUESTED** [review]

File: Assets/MirageXR/ContentTypes/3DModel/Model.cs (hunk 1 above)
Comment (fwild) [reply Assets/MirageXR/ContentTypes/3DModel/Model.cs]: I checked carefully - deleting, adding, keep alive, upload/download, all works. Merging.
