### PR TITLE
1689 fixes MoodleManager hit counter error

### LINKED ISSUE #1689: MoodleManager: tries to increase hit counter on server for local activity
Moodle Manager throws an error on the console log when trying to increase the hit counter on the server for an activity that is not yet uploaded, and only locally saved. Expected behaviour: should check if the activity is uploaded before attempting to increase the hit count? Or simply not throw an error.

### PR DESCRIPTION
**Pull request by fwild**
MoodleManager tried to increase the hit counter also for local activities, throwing an error. 

Fixes #1689 by adding a boolean flag to the UpdateViewsOfActivity method to indicate whether the activity existsRemotely.

### CODE REVIEW

File: Assets/MirageXR/Services/Moodle/MoodleManager.cs [hunk 1]
```diff
@@ -264,7 +271,13 @@ private static List<Session> ParseArlemListJson(string json)
             }
             catch (Exception e)
             {
-                Debug.LogError($"[MoodleManager] ParseArlemListJson error\nmessage: {e}");
+                RootView_v2.Instance.dialog.ShowMiddle(
+                    "Network Error",
+                    "Could not connect to server, showing local activities only.",
+                    "OK", () => AppLog.LogInfo("[MoodleManager] User acknowledged network error"),
+                    "Cancel", () => AppLog.LogInfo("[MoodleManager] User acknowledged network error"),
+                    true);
```
Comment (cawke) [inline Assets/MirageXR/Services/Moodle/MoodleManager.cs]:
```suggestion
                RootView_v2.Instance.dialog.ShowMiddle(
                    "Network Error",
                    "Could not connect to server, showing local activities only.",
                    "OK", () => AppLog.LogInfo("[MoodleManager] User acknowledged network error")
                    true);
```

the dialog now supports a one-button window

**Review by cawke — CHANGES_REQUESTED** [review]
